### ISSUE TITLE
Action fails with no output

### ISSUE THREAD

**Issue by countless-integers** [sourcetoad/aws-codedeploy-action#30]
I've tried steps recommended in https://github.com/sourcetoad/aws-codedeploy-action/issues/29 , but I still can't tell what's going wrong. I've added debug secret variables and I'm using v1.0.3 of this action. 

This is the most verbose output I could get out of the action 

```
...
##[debug]Input variables correctly validated.
##[debug]Zip directory located (with appspec.yml).
##[debug]Exclusion file created for files to ignore in Zip Generation.
##[debug]Zip Archive created.
##[debug]Zip Archived validated.
##[debug]Docker Action run completed with exit code 1
##[debug]Finishing: AWS CodeDeploy
```

In CodeDeploy panel I see no new releases. Bucket name is correct, policy gives access to it, AWS credentials also seem correct.

Any idea how can I debug this?

**Comment by iBotPeaches** [comment]
> Any idea how can I debug this?

Thanks, looking at your output it appears to be dying right at the upload to S3. I will work on a patch that doesn't eat that error message up so we can output it into the script. That will help give the exact message of what is going wrong.

The line at fault is here - https://github.com/sourcetoad/aws-codedeploy-action/blob/master/deploy.sh#L88. Will get a fix up.

**Comment by iBotPeaches** [comment]
I put up a PR that simply just removes that clobbering of output. You could try that branch using `sourcetoad/aws-codedeploy-action@issue-30`

**Comment by countless-integers** [comment]
Yep, I used an encrypted bucket for artifact storage and the deployment user was missing a policy assignment to decrypt stuff and that's why it was failing for me. Extra output helped.
