### ISSUE TITLE
Missing CodeDeploy permissions in recommended IAM policy in README (?)

### ISSUE THREAD

**Issue by countless-integers** [sourcetoad/aws-codedeploy-action#32]
[Readme](https://github.com/sourcetoad/aws-codedeploy-action#iam-permissions) mentions S3 permission, but not exact CodeDeploy permissions. 

I know it needs at least:

* `codedeploy:RegisterApplicationRevision` for applcations 
* `codedeploy:CreateDeployment` and list deployments (I just used `codedeploy:List*`) for deployment groups

I'd make a PR, but I'm not sure what the exact policies are, because took a bit of a shortcut and used some `*` and permissions I used for a previous implementation I was using.

**Comment by iBotPeaches** [comment]
thanks for the note. Appears I only put docs about the s3 permissions. I have a PR up for the associated codedeploy suggested permissions.
