### ISSUE TITLE
AppSpec.yml not located at

### ISSUE THREAD

**Issue by sis-mvador** [sourcetoad/aws-codedeploy-action#34]
Unable to fix this issue -

appspec.yml was not located at: ./

<img width="771" alt="Screen Shot 2021-05-23 at 3 48 12 PM" src="https://user-images.githubusercontent.com/71389044/119274545-71202d00-bbde-11eb-9c83-21e3c24b8376.png">
<img width="910" alt="Screen Shot 2021-05-23 at 3 48 29 PM" src="https://user-images.githubusercontent.com/71389044/119274546-71202d00-bbde-11eb-8938-5c58bba7f70d.png">

**Comment by iBotPeaches** [comment]
Hmm. Can't seem to replicate that on the sets of projects we use this one. Do you have a redacted snippet of calling the workflow?

**Comment by sis-mvador** [comment]
Here is the screenshot of my workflow. May be you can spot something I might be missing.

![Screen Shot 2021-05-24 at 9 42 57 PM](https://user-images.githubusercontent.com/71389044/119427432-03a4f700-bcd9-11eb-8a76-f393265ebcbc.png)

**Comment by iBotPeaches** [comment]
Looks like you forgot to check out the repo. I see it on the first job (`continuous-integration`) but not the 2nd (`continuous-deployment`)

**Comment by iBotPeaches** [comment]
Hope that helped. Going to close this as I haven't heard anything in a week.
