### ISSUE TITLE
Request: Integrate with configure-aws-credentials

### ISSUE THREAD

**Issue by lscerrigdc** [sourcetoad/aws-codedeploy-action#52]
It would be nice if the task could use the credentials set up by the
https://github.com/aws-actions/configure-aws-credentials task.
This would help avoid having to refresh the secret in the repo settings and use AWS roles instead

**Comment by iBotPeaches** [comment]
Thanks for the request!

This does look like something we can investigate and look for.

**Comment by iBotPeaches** [comment]
I took a look and it looks like we have a two options.

1. Remove authentication from this package, asking users to use the linked package to setup authentication prior and we piggyback off it of it for our `aws-cli` calls.
2. Update our package to allow nullable `secret` and `access` creds, so interested users can use an alternative method that gives authentication to `aws-cli`.

I'm thinking the 2nd path for least resistance, but also the 1st path if we making a new major version and then remove all use of having to cleanse/purge access keys in bash.

**Comment by iBotPeaches** [comment]
We are going to make a new major v2 version that enforces the use of the `configure-aws-credentials` prior to our action. This looks to be most secure and how we can evolve build scripts to be most hardened.
