### ISSUE TITLE
How to disable polling

### ISSUE THREAD

**Issue by Samuell1** [sourcetoad/aws-codedeploy-action#57]
Hey, thanks for the amazing package!

I was thinking if there is a way to disable polling to save a action minutes. I tried to setting `max_polling_iterations` to `0` but then it errors out that deployment wasnt successfull, except deployment on codedeploy works fine.

**Comment by iBotPeaches** [comment]
Ah never considered a 0 option. We can slip that into our upcoming release. Give me a few days.

**Comment by Samuell1** [comment]
@iBotPeaches Thanks a lot!

**Comment by Samuell1** [comment]
If you need testing new version just let me know i will try it out.

**Comment by Samuell1** [comment]
Yes it works!

**Comment by iBotPeaches** [comment]
Thanks. We have a few internal tests to run and then we will release a new tag and move the "v1" tag.
