### ISSUE TITLE
S3 step

### ISSUE THREAD

**Issue by dcorrea777** [sourcetoad/aws-codedeploy-action#86]
Hi, I have the following question!

From what I understand, this action, in addition to deploying, also compresses the application first and sends it to s3, correct? I'm wanting to use this action, but I already sent my application to s3 in a previous step, is it possible to just use deploy?

**Comment by iBotPeaches** [comment]
Hi @dcorrea777,

The action only has 2 different behaviors and I don't think either are what you are looking for.

 * Default (as you saw) - creates/zips/uploads the intended deployment
 * Archive (`archive`) - it trusts that provided file is the deployment and uploads that
 
 It does not support at present any method of just deploying something from an already named/uploaded S3 asset.

**Comment by dcorrea777** [comment]
Cool, thanks a lot for answering @iBotPeaches
